import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy — Zoom City',
  description: 'How Zoom City collects, uses, and protects your personal data.',
}

export default function PrivacyPolicyPage() {
  return (
    <>
      <style>{`
        .legal-page {
          min-height: 100vh;
          background: linear-gradient(160deg, #161622 0%, #073B4C 100%);
          font-family: var(--font-dm-sans), sans-serif;
          color: rgba(205, 205, 224, 0.85);
          padding: 56px 24px 80px;
        }
        .legal-container {
          max-width: 760px;
          margin: 0 auto;
        }
        .legal-title {
          font-family: var(--font-bebas-neue), sans-serif;
          font-size: clamp(2.2rem, 6vw, 3.2rem);
          color: #FFF32B;
          letter-spacing: 0.03em;
          margin-bottom: 8px;
          line-height: 1.05;
        }
        .legal-updated {
          color: rgba(205,205,224,0.45);
          font-size: 0.85rem;
          margin-bottom: 36px;
        }
        .legal-intro {
          font-size: 1rem;
          line-height: 1.7;
          margin-bottom: 40px;
          color: rgba(205,205,224,0.8);
        }
        .legal-section {
          margin-bottom: 30px;
        }
        .legal-section h2 {
          display: flex;
          align-items: center;
          gap: 10px;
          font-size: 1.15rem;
          font-weight: 700;
          color: #ffffff;
          margin-bottom: 10px;
        }
        .legal-section h2::before {
          content: '';
          width: 6px;
          height: 6px;
          border-radius: 50%;
          background: #FFF32B;
          flex-shrink: 0;
        }
        .legal-section p, .legal-section li {
          font-size: 0.95rem;
          line-height: 1.7;
          color: rgba(205,205,224,0.8);
        }
        .legal-section p + p {
          margin-top: 12px;
        }
        .legal-section ul {
          margin: 10px 0 0 0;
          padding-left: 20px;
        }
        .legal-section li {
          margin-bottom: 4px;
        }
        .legal-email {
          color: #FFF32B;
          font-weight: 700;
          text-decoration: none;
        }
        .legal-email:hover {
          text-decoration: underline;
        }
        .legal-back {
          display: inline-block;
          margin-top: 48px;
          color: rgba(205,205,224,0.4);
          font-size: 0.85rem;
          text-decoration: none;
          transition: color 0.2s;
        }
        .legal-back:hover { color: #FFF32B; }
      `}</style>

      <main className="legal-page">
        <div className="legal-container">
          <h1 className="legal-title">Privacy Policy</h1>
          <p className="legal-updated">Last updated: July 25, 2026</p>

          <p className="legal-intro">
            This Privacy Policy describes our policies and procedures on the
            collection, use and disclosure of your information when you use
            the Zoom City application (the &quot;Service&quot;), and tells you
            about your privacy rights and how the law protects you. We use
            your personal data to provide and improve the Service. By using
            the Service, you agree to the collection and use of information
            in accordance with this Privacy Policy.
          </p>

          <section className="legal-section">
            <h2>Interpretation and Definitions</h2>
            <p>
              The words of which the initial letter is capitalized have
              meanings defined under the following conditions. The following
              definitions shall have the same meaning regardless of whether
              they appear in singular or in plural.
            </p>
            <ul>
              <li><strong>Account</strong> means a unique account created for you to access our Service.</li>
              <li><strong>Application</strong> refers to Zoom City, the software program provided by the Company.</li>
              <li><strong>Company</strong> (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) refers to Zoom City.</li>
              <li><strong>Country</strong> refers to Serbia.</li>
              <li><strong>Device</strong> means any device that can access the Service, such as a computer or a mobile phone.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Application.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes data on behalf of the Company.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong>You</strong> means the individual accessing or using the Service.</li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>Collecting and Using Your Personal Data</h2>
            <p>
              While using our Service, we may ask you to provide certain
              personally identifiable information, including your email
              address, first and last name, and Usage Data.
            </p>
            <p>
              Usage Data is collected automatically when using the Service,
              and may include information such as your device&apos;s IP
              address, browser type, device information, the time and date of
              your visit, and other diagnostic data.
            </p>
          </section>

          <section className="legal-section">
            <h2>Information Collected while Using the Application</h2>
            <p>
              With your permission, the Application may access your device&apos;s
              camera, microphone, photo/video gallery, and location, in order
              to let you record and share video reels, upload cover photos,
              and discover cities near you. You may enable or disable access
              to this information at any time through your device settings.
            </p>
          </section>

          <section className="legal-section">
            <h2>Use of Your Personal Data</h2>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul>
              <li>To provide and maintain our Service, including monitoring its usage.</li>
              <li>To manage your Account and your registration as a user of the Service.</li>
              <li>To contact you by email, push notification, or other equivalent forms of electronic communication.</li>
              <li>To manage your requests and provide customer support.</li>
              <li>For data analysis and to improve the Service.</li>
            </ul>
            <p>
              We may share your personal information with service providers,
              affiliates, business partners, other users (for content you
              choose to make public, such as video reels and profile
              information), or with your consent.
            </p>
          </section>

          <section className="legal-section">
            <h2>Retention and Transfer of Your Personal Data</h2>
            <p>
              The Company will retain your Personal Data only for as long as
              is necessary for the purposes set out in this Privacy Policy,
              or as needed to comply with legal obligations. Your information
              may be processed in countries other than your own; by using
              the Service, you agree to this transfer.
            </p>
          </section>

          <section className="legal-section">
            <h2>Delete Your Personal Data</h2>
            <p>
              You may request the deletion of the personal data we have
              collected about you at any time, directly within the app
              (Profile → Account settings) or by contacting us. Some data may
              be retained where we have a legal obligation or lawful basis to
              do so.
            </p>
          </section>

          <section className="legal-section">
            <h2>Security of Your Personal Data</h2>
            <p>
              The security of your Personal Data is important to us, but
              remember that no method of transmission over the internet or
              method of electronic storage is 100% secure. While we strive
              to use commercially acceptable means to protect your Personal
              Data, we cannot guarantee its absolute security.
            </p>
          </section>

          <section className="legal-section">
            <h2>Children&apos;s Privacy</h2>
            <p>
              Our Service does not address anyone under the age of 13. We do
              not knowingly collect personally identifiable information from
              anyone under the age of 13. If you are a parent or guardian and
              believe your child has provided us with personal data, please
              contact us.
            </p>
          </section>

          <section className="legal-section">
            <h2>Changes to this Privacy Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. We will
              notify you by updating the &quot;Last updated&quot; date at the
              top of this page. You are advised to review this page
              periodically for any changes.
            </p>
          </section>

          <section className="legal-section">
            <h2>Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, you can
              contact us by email:{' '}
              <a className="legal-email" href="mailto:zoomcityapk@gmail.com">
                zoomcityapk@gmail.com
              </a>
            </p>
          </section>

          <a href="/" className="legal-back">← Back to zoomcity.app</a>
        </div>
      </main>
    </>
  )
}
